# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "afe2b2ee97a64d42e3f071170c5962be"
name = "checkout-deploy-2"
handle = "checkout-deploy-2"
application_url = "https://pda-lives-nomination-least.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations,write_discounts,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://pda-lives-nomination-least.trycloudflare.com/auth/callback",
  "https://pda-lives-nomination-least.trycloudflare.com/auth/shopify/callback",
  "https://pda-lives-nomination-least.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
