# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "236e532e828e3c9853c7e207279c37eb"
name = "Checkout Deploy"
handle = "checkout-deploy-1"
application_url = "https://dennis-semester-ebony-fisheries.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkout_branding_settings,write_checkout_branding_settings,write_checkouts,write_delivery_customizations,write_discounts,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://dennis-semester-ebony-fisheries.trycloudflare.com/auth/callback",
  "https://dennis-semester-ebony-fisheries.trycloudflare.com/auth/shopify/callback",
  "https://dennis-semester-ebony-fisheries.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://dennis-semester-ebony-fisheries.trycloudflare.com/api"
subpath = "api"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true
