# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "76b38acc3a61143bfdfc236b65ac1968"
name = "checkout-beta"
handle = "checkout-beta-1"
application_url = "https://feels-liverpool-alt-helped.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://feels-liverpool-alt-helped.trycloudflare.com/auth/callback",
  "https://feels-liverpool-alt-helped.trycloudflare.com/auth/shopify/callback",
  "https://feels-liverpool-alt-helped.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
