# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

[[extensions]]
name = "payment-icons"
handle = "payment-icons"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

[extensions.settings]
    [[extensions.settings.fields]]
    key = "banner_title"
    type = "single_line_text_field"
    name = "Banner title"
    description = "Enter a title for the banner"

    [[extensions.settings.fields]]
    key = "image_1_icon"
    type = "single_line_text_field"
    name = "Image #1 Icon"
    description = "Available options: none, affin-bank, alipay, airtel-money, afterpay, akulaku, amazon, american-express, apple-pay, facebook-pay"

    [[extensions.settings.fields]]
    key = "image_2_icon"
    type = "single_line_text_field"
    name = "Image #2 Icon"
    description = "Available options: none, affin-bank, alipay, airtel-money, afterpay, akulaku, amazon, american-express, apple-pay, facebook-pay"

    [[extensions.settings.fields]]
    key = "image_3_icon"
    type = "single_line_text_field"
    name = "Image #3 Icon"
    description = "Available options: none, affin-bank, alipay, airtel-money, afterpay, akulaku, amazon, american-express, apple-pay, facebook-pay"

    [[extensions.settings.fields]]
    key = "image_4_icon"
    type = "single_line_text_field"
    name = "Image #4 Icon"
    description = "Available options: none, affin-bank, alipay, airtel-money, afterpay, akulaku, amazon, american-express, apple-pay, facebook-pay"

    [[extensions.settings.fields]]
    key = "image_5_icon"
    type = "single_line_text_field"
    name = "Image #5 Icon"
    description = "Available options: none, affin-bank, alipay, airtel-money, afterpay, akulaku, amazon, american-express, apple-pay, facebook-pay"
